/soc/oplus,pps_charge/oplus,pps_full_normal_sw_vbat_third 0x1208
/soc/oplus,pps_charge/oplus,pps_full_normal_hw_vbat 0x1208
/soc/oplus,pps_charge/oplus,pps_full_normal_sw_vbat 0x1208
/soc/oplus,pps_charge/oplus,soc_range 0x00 0x1e 0x50 0x5f
/soc/oplus,pps_charge/oplus,curr_max_ma 0x1a90
/soc/oplus,pps_charge/oplus,pps_charge_strategy_temp 0x37 0x37 0x82 0xaa 0x168 0x1e0 0x208
/soc/oplus,pps_charge/oplus,pps_over_high_or_low_current 0x1a90
/soc/oplus,pps_charge/oplus,pps_ibat_over_third 0x2710
/soc/oplus,pps_charge/pps_charge_oplus_strategy/oplus,temp_range 0x45 0x45 0x87 0xad 0x172 0x1c8 0x210
/soc/oplus,pps_charge/pps_charge_oplus_strategy/oplus,soc_range 0x00 0x14 0x37 0x55 0x5a
