/soc/oplus,ufcs_charge/oplus,ufcs_strategy_high_current 0x1c84 0xfa0 0xbb8 0x1c84 0x1388 0xfa0
/soc/oplus,ufcs_charge/oplus,subboard_ntc_abnormal_current 0x1388
/soc/oplus,ufcs_charge/oplus_spec,ufcs_low_temp 0x34
/soc/oplus,ufcs_charge/oplus,ufcs_full_normal_hw_vbat 0x11f8
/soc/oplus,ufcs_charge/oplus,ufcs_full_normal_sw_vbat 0x11f8
/soc/oplus,ufcs_charge/oplus,ufcs_full_warm_vbat 0x1086
/soc/oplus,ufcs_charge/oplus,temperature_strategy_data 0x01 0x00 0x163 0x1ae 0x01 0x00 0x1a9 0x1b8 0x1388 0x02 0x00 0x1b8 0x1cc 0xfa0 0x03 0x01 0x1c7 0x1d1 0xfa0 0x04 0x02 0x1d1 0x1d6 0xbb8 0x04 0x03
/soc/oplus,ufcs_charge/oplus,ufcs_charge_strategy_temp 0x32 0x32 0x78 0xa0 0x15e 0x1d6 0x1fe
/soc/oplus,ufcs_charge/oplus,ufcs_strategy_batt_high_temp 0x1a4 0x1b8 0x1d6 0x19f 0x1b8 0x1d6
/soc/oplus,ufcs_charge/oplus,ufcs_full_normal_hw_vbat_third 0x11f8
/soc/oplus,ufcs_charge/oplus,ufcs_full_normal_sw_vbat_third 0x11ee

